import { ButtonHTMLAttributes, FC } from 'react';
import { IAlignItems, IAlignSelf, IBorderRadius, IBorderWidth, IColor, IDistance, IHeight, IJustifyContent, IWidth } from '../types';
export interface IBaseButtonProps extends ButtonHTMLAttributes<HTMLButtonElement> {
    align?: IAlignItems;
    alignSelf?: IAlignSelf;
    backgroundColor?: IColor;
    borderColor?: IColor;
    borderRadius?: IBorderRadius | number;
    borderWidth?: IBorderWidth | number;
    color?: IColor;
    fullHeight?: boolean;
    fullWidth?: boolean;
    grow?: number;
    height?: IHeight | number;
    justify?: IJustifyContent;
    marginBottom?: IDistance | number;
    marginLeft?: IDistance | number;
    marginRight?: IDistance | number;
    marginTop?: IDistance | number;
    marginX?: IDistance | number;
    marginY?: IDistance | number;
    maxHeight?: IHeight | number;
    maxWidth?: IWidth | number;
    minHeight?: IHeight | number;
    minWidth?: IWidth | number;
    paddingBottom?: IDistance | number;
    paddingLeft?: IDistance | number;
    paddingRight?: IDistance | number;
    paddingTop?: IDistance | number;
    paddingX?: IDistance | number;
    paddingY?: IDistance | number;
    shrink?: number;
    width?: IWidth | number;
}
export declare type IExternalBaseButtonProps = Omit<IBaseButtonProps, 'align' | 'backgroundColor' | 'color' | 'justify' | 'paddingBottom' | 'paddingLeft' | 'paddingRight' | 'paddingTop' | 'paddingX' | 'paddingY'>;
export declare const BaseButton: FC<IBaseButtonProps>;
