"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.EasyFlexContext = exports.defaultEasyFlexTheme = exports.themeSizes = exports.colorNames = exports.colorKeywords = exports.globalValues = void 0;
var react_1 = require("react");
exports.globalValues = ['inherit', 'initial', 'revert', 'revert-layer', 'unset'];
exports.colorKeywords = ['currentColor', 'transparent'];
exports.colorNames = [
    'aliceblue',
    'antiquewhite',
    'aqua',
    'aquamarine',
    'azure',
    'beige',
    'bisque',
    'black',
    'blanchedalmond',
    'blue',
    'blueviolet',
    'brown',
    'burlywood',
    'cadetblue',
    'chartreuse',
    'chocolate',
    'coral',
    'cornflowerblue',
    'cornsilk',
    'crimson',
    'cyan',
    'darkblue',
    'darkcyan',
    'darkgoldenrod',
    'darkgray',
    'darkgreen',
    'darkgrey',
    'darkkhaki',
    'darkmagenta',
    'darkolivegreen',
    'darkorange',
    'darkorchid',
    'darkred',
    'darksalmon',
    'darkseagreen',
    'darkslateblue',
    'darkslategray',
    'darkslategrey',
    'darkturquoise',
    'darkviolet',
    'deeppink',
    'deepskyblue',
    'dimgray',
    'dimgrey',
    'dodgerblue',
    'firebrick',
    'floralwhite',
    'forestgreen',
    'fuchsia',
    'gainsboro',
    'ghostwhite',
    'gold',
    'goldenrod',
    'gray',
    'green',
    'greenyellow',
    'grey',
    'honeydew',
    'hotpink',
    'indianred',
    'indigo',
    'ivory',
    'khaki',
    'lavender',
    'lavenderblush',
    'lawngreen',
    'lemonchiffon',
    'lightblue',
    'lightcoral',
    'lightcyan',
    'lightgoldenrodyellow',
    'lightgray',
    'lightgreen',
    'lightgrey',
    'lightpink',
    'lightsalmon',
    'lightseagreen',
    'lightskyblue',
    'lightslategray',
    'lightslategrey',
    'lightsteelblue',
    'lightyellow',
    'lime',
    'limegreen',
    'linen',
    'magenta',
    'maroon',
    'mediumaquamarine',
    'mediumblue',
    'mediumorchid',
    'mediumpurple',
    'mediumseagreen',
    'mediumslateblue',
    'mediumspringgreen',
    'mediumturquoise',
    'mediumvioletred',
    'midnightblue',
    'mintcream',
    'mistyrose',
    'moccasin',
    'navajowhite',
    'navy',
    'oldlace',
    'olive',
    'olivedrab',
    'orange',
    'orangered',
    'orchid',
    'palegoldenrod',
    'palegreen',
    'paleturquoise',
    'palevioletred',
    'papayawhip',
    'peachpuff',
    'peru',
    'pink',
    'plum',
    'powderblue',
    'purple',
    'rebeccapurple',
    'red',
    'rosybrown',
    'royalblue',
    'saddlebrown',
    'salmon',
    'sandybrown',
    'seagreen',
    'seashell',
    'sienna',
    'silver',
    'skyblue',
    'slateblue',
    'slategray',
    'slategrey',
    'snow',
    'springgreen',
    'steelblue',
    'tan',
    'teal',
    'thistle',
    'tomato',
    'turquoise',
    'violet',
    'wheat',
    'white',
    'whitesmoke',
    'yellow',
    'yellowgreen', // #9acd32
];
exports.themeSizes = [
    '8xs',
    '7xs',
    '6xs',
    '5xs',
    '4xs',
    '3xs',
    'xxs',
    'xs',
    's',
    'm',
    'l',
    'xl',
    'xxl',
    '3xl',
    '4xl',
    '5xl',
    '6xl',
    '7xl',
    '8xl',
];
exports.defaultEasyFlexTheme = {
    border: {
        defaultStyle: 'solid',
        radius: {
            '8xs': '0px',
            '7xs': '0px',
            '6xs': '0px',
            '5xs': '0px',
            '4xs': '0px',
            '3xs': '0px',
            xxs: '0px',
            xs: '0px',
            s: '0px',
            m: '0px',
            l: '0px',
            xl: '0px',
            xxl: '0px',
            '3xl': '0px',
            '4xl': '0px',
            '5xl': '0px',
            '6xl': '0px',
            '7xl': '0px',
            '8xl': '0px',
            round: '99999px',
        },
        width: {
            '8xs': '1px',
            '7xs': '1px',
            '6xs': '1px',
            '5xs': '1px',
            '4xs': '1px',
            '3xs': '1px',
            xxs: '1px',
            xs: '1px',
            s: '1px',
            m: '1px',
            l: '1px',
            xl: '1px',
            xxl: '1px',
            '3xl': '1px',
            '4xl': '1px',
            '5xl': '1px',
            '6xl': '1px',
            '7xl': '1px',
            '8xl': '1px',
        },
    },
    color: {},
    distance: {
        '8xs': '1px',
        '7xs': '2px',
        '6xs': '3px',
        '5xs': '5px',
        '4xs': '7px',
        '3xs': '10px',
        xxs: '15px',
        xs: '23px',
        s: '34px',
        m: '51px',
        l: '77px',
        xl: '115px',
        xxl: '173px',
        '3xl': '259px',
        '4xl': '389px',
        '5xl': '584px',
        '6xl': '876px',
        '7xl': '1314px',
        '8xl': '1971px',
    },
    font: {
        family: {},
        lineHeight: {
            '8xs': 1.5,
            '7xs': 1.5,
            '6xs': 1.5,
            '5xs': 1.5,
            '4xs': 1.5,
            '3xs': 1.5,
            xxs: 1.5,
            xs: 1.5,
            s: 1.5,
            m: 1.5,
            l: 1.5,
            xl: 1.5,
            xxl: 1.5,
            '3xl': 1.5,
            '4xl': 1.5,
            '5xl': 1.5,
            '6xl': 1.5,
            '7xl': 1.5,
            '8xl': 1.5,
        },
        size: {
            '8xs': '0.4375rem',
            '7xs': '0.5rem',
            '6xs': '0.5625rem',
            '5xs': '0.625rem',
            '4xs': '0.6875rem',
            '3xs': '0.75rem',
            xxs: '0.8125rem',
            xs: '0.875rem',
            s: '0.9375rem',
            m: '1rem',
            l: '1.125rem',
            xl: '1.25rem',
            xxl: '1.375rem',
            '3xl': '1.5rem',
            '4xl': '1.75rem',
            '5xl': '2rem',
            '6xl': '2.5rem',
            '7xl': '3rem',
            '8xl': '4rem', // 64px
        },
        weight: {
            thin: 100,
            extraLight: 200,
            light: 300,
            normal: 400,
            medium: 500,
            semibold: 600,
            bold: 700,
            extraBold: 800,
            black: 900,
            extraBlack: 950,
        },
    },
    modal: {
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        blur: '0px',
        containerElementId: '',
    },
    size: {
        aspectRatio: {},
        height: {
            '8xs': '1px',
            '7xs': '2px',
            '6xs': '3px',
            '5xs': '5px',
            '4xs': '7px',
            '3xs': '10px',
            xxs: '15px',
            xs: '23px',
            s: '34px',
            m: '51px',
            l: '77px',
            xl: '115px',
            xxl: '173px',
            '3xl': '259px',
            '4xl': '389px',
            '5xl': '584px',
            '6xl': '876px',
            '7xl': '1314px',
            '8xl': '1971px',
        },
        width: {
            '8xs': '1px',
            '7xs': '2px',
            '6xs': '3px',
            '5xs': '5px',
            '4xs': '7px',
            '3xs': '10px',
            xxs: '15px',
            xs: '23px',
            s: '34px',
            m: '51px',
            l: '77px',
            xl: '115px',
            xxl: '173px',
            '3xl': '259px',
            '4xl': '389px',
            '5xl': '584px',
            '6xl': '876px',
            '7xl': '1314px',
            '8xl': '1971px',
        },
    },
    viewport: {
        threshold: {
            '8xs': 429,
            '7xs': 429,
            '6xs': 429,
            '5xs': 429,
            '4xs': 429,
            '3xs': 429,
            xxs: 429,
            xs: 640,
            s: 768,
            m: 1024,
            l: 1280,
            xl: 1536,
            xxl: 1536,
            '3xl': 1536,
            '4xl': 1536,
            '5xl': 1536,
            '6xl': 1536,
            '7xl': 1536,
            '8xl': 1536,
        },
    },
};
exports.EasyFlexContext = (0, react_1.createContext)(exports.defaultEasyFlexTheme);
