export declare type IDeepPartial<T> = T extends object ? {
    [P in keyof T]?: IDeepPartial<T[P]>;
} : T;
export declare type IBaseSize = '8xs' | '7xs' | '6xs' | '5xs' | '4xs' | '3xs' | 'xxs' | 'xs' | 's' | 'm' | 'l' | 'xl' | 'xxl' | '3xl' | '4xl' | '5xl' | '6xl' | '7xl' | '8xl';
export interface IBaseSizeNumber {
    '8xs': number;
    '7xs': number;
    '6xs': number;
    '5xs': number;
    '4xs': number;
    '3xs': number;
    xxs: number;
    xs: number;
    s: number;
    m: number;
    l: number;
    xl: number;
    xxl: number;
    '3xl': number;
    '4xl': number;
    '5xl': number;
    '6xl': number;
    '7xl': number;
    '8xl': number;
}
export declare type ISizeType = 'px' | 'rem';
export declare type IAlignItems = 'baseline' | 'center' | 'flex-end' | 'flex-start' | 'stretch';
export declare type IAlignSelf = 'auto' | 'baseline' | 'center' | 'flex-end' | 'flex-start' | 'stretch';
export declare type IFlexDirection = 'column' | 'column-reverse' | 'row' | 'row-reverse';
export declare type IJustifyContent = 'center' | 'flex-end' | 'flex-start' | 'space-around' | 'space-between' | 'space-evenly';
export declare type IOverflow = 'auto' | 'hidden' | 'scroll' | 'visible';
export declare type ITextAlign = 'center' | 'end' | 'justify' | 'justify-all' | 'left' | 'match-parent' | 'right' | 'start';
export declare type IWordBreak = 'break-all' | 'break-word' | 'keep-all' | 'normal';
export declare type IBaseFlexElement = 'article' | 'aside' | 'div' | 'figure' | 'footer' | 'header' | 'main' | 'nav' | 'section' | 'summary';
export declare type IBorderRadius = IBaseSize;
export declare type IBorderWidth = IBaseSize;
export declare type IBaseColor = 'primary' | 'secondary' | 'tertiary' | 'quaternary' | 'quinary' | 'senary' | 'warning' | 'error' | 'header' | 'footer' | 'modal' | 'primaryText' | 'secondaryText' | 'tertiaryText' | 'quaternaryText' | 'quinaryText' | 'senaryText' | 'warningText' | 'errorText' | 'headerText' | 'footerText' | 'modalText' | 'primaryBackground' | 'secondaryBackground' | 'tertiaryBackground' | 'quaternaryBackground' | 'quinaryBackground' | 'senaryBackground' | 'warningBackground' | 'errorBackground' | 'headerBackground' | 'footerBackground' | 'modalBackground' | 'onPrimary' | 'onSecondary' | 'onTertiary' | 'onQuaternary' | 'onQuinary' | 'onSenary' | 'onWarning' | 'onError' | 'onHeader' | 'onFooter' | 'onModal' | 'primaryBorder' | 'secondaryBorder' | 'tertiaryBorder' | 'quaternaryBorder' | 'senaryBorder' | 'warningBorder' | 'errorBorder' | 'headerBorder' | 'footerBorder' | 'modalBorder';
export declare type IColorCode = `#${string}` | `hsl(${number}, ${number}%, ${number}%)` | `hsla(${number}, ${number}%, ${number}%, ${number})` | `rgb(${number}, ${number}, ${number})` | `rgb(${number}%, ${number}%, ${number}%)` | `rgb(${number} ${number} ${number})` | `rgb(${number}% ${number}% ${number}%)` | `rgb(${number}, ${number}, ${number}, ${number})` | `rgb(${number}, ${number}, ${number}, ${number}%)` | `rgb(${number}%, ${number}%, ${number}%, ${number})` | `rgb(${number}%, ${number}%, ${number}%, ${number}%)` | `rgb(${number} ${number} ${number} / ${number})` | `rgb(${number} ${number} ${number} / ${number}%)` | `rgb(${number}% ${number}% ${number}% / ${number})` | `rgb(${number}% ${number}% ${number}% / ${number}%)` | `rgba(${number}, ${number}, ${number})` | `rgba(${number}%, ${number}%, ${number}%)` | `rgba(${number} ${number} ${number})` | `rgba(${number}% ${number}% ${number}%)` | `rgba(${number}, ${number}, ${number}, ${number})` | `rgba(${number}, ${number}, ${number}, ${number}%)` | `rgba(${number}%, ${number}%, ${number}%, ${number})` | `rgba(${number}%, ${number}%, ${number}%, ${number}%)` | `rgba(${number} ${number} ${number} / ${number})` | `rgba(${number} ${number} ${number} / ${number}%)` | `rgba(${number}% ${number}% ${number}% / ${number})` | `rgba(${number}% ${number}% ${number}% / ${number}%)`;
export declare type IColorKeyword = 'currentColor' | 'inherit' | 'transparent';
export declare type IColorName = 'aliceblue' | 'antiquewhite' | 'aqua' | 'aquamarine' | 'azure' | 'beige' | 'bisque' | 'black' | 'blanchedalmond' | 'blue' | 'blueviolet' | 'brown' | 'burlywood' | 'cadetblue' | 'chartreuse' | 'chocolate' | 'coral' | 'cornflowerblue' | 'cornsilk' | 'crimson' | 'cyan' | 'darkblue' | 'darkcyan' | 'darkgoldenrod' | 'darkgray' | 'darkgreen' | 'darkgrey' | 'darkkhaki' | 'darkmagenta' | 'darkolivegreen' | 'darkorange' | 'darkorchid' | 'darkred' | 'darksalmon' | 'darkseagreen' | 'darkslateblue' | 'darkslategray' | 'darkslategrey' | 'darkturquoise' | 'darkviolet' | 'deeppink' | 'deepskyblue' | 'dimgray' | 'dimgrey' | 'dodgerblue' | 'firebrick' | 'floralwhite' | 'forestgreen' | 'fuchsia' | 'gainsboro' | 'ghostwhite' | 'gold' | 'goldenrod' | 'gray' | 'green' | 'greenyellow' | 'grey' | 'honeydew' | 'hotpink' | 'indianred' | 'indigo' | 'ivory' | 'khaki' | 'lavender' | 'lavenderblush' | 'lawngreen' | 'lemonchiffon' | 'lightblue' | 'lightcoral' | 'lightcyan' | 'lightgoldenrodyellow' | 'lightgray' | 'lightgreen' | 'lightgrey' | 'lightpink' | 'lightsalmon' | 'lightseagreen' | 'lightskyblue' | 'lightslategray' | 'lightslategrey' | 'lightsteelblue' | 'lightyellow' | 'lime' | 'limegreen' | 'linen' | 'magenta' | 'maroon' | 'mediumaquamarine' | 'mediumblue' | 'mediumorchid' | 'mediumpurple' | 'mediumseagreen' | 'mediumslateblue' | 'mediumspringgreen' | 'mediumturquoise' | 'mediumvioletred' | 'midnightblue' | 'mintcream' | 'mistyrose' | 'moccasin' | 'navajowhite' | 'navy' | 'oldlace' | 'olive' | 'olivedrab' | 'orange' | 'orangered' | 'orchid' | 'palegoldenrod' | 'palegreen' | 'paleturquoise' | 'palevioletred' | 'papayawhip' | 'peachpuff' | 'peru' | 'pink' | 'plum' | 'powderblue' | 'purple' | 'rebeccapurple' | 'red' | 'rosybrown' | 'royalblue' | 'saddlebrown' | 'salmon' | 'sandybrown' | 'seagreen' | 'seashell' | 'sienna' | 'silver' | 'skyblue' | 'slateblue' | 'slategray' | 'slategrey' | 'snow' | 'springgreen' | 'steelblue' | 'tan' | 'teal' | 'thistle' | 'tomato' | 'turquoise' | 'violet' | 'wheat' | 'white' | 'whitesmoke' | 'yellow' | 'yellowgreen';
export declare type IColor = IBaseColor | IColorCode | IColorKeyword | IColorName;
export declare type IDistance = IBaseSize;
export declare type IFlipDirection = 'flip' | 'flip-reverse' | 'reverse';
export declare type IFontSize = IBaseSize;
export declare type IFontStyle = 'italic' | 'normal';
export declare type IFontWeight = 'bold' | 'normal' | 'semibold';
export declare type IHeight = IBaseSize;
export declare type IStyleElement = 'b' | 'cite' | 'code' | 'em' | 'i' | 'kbd' | 'mark' | 's' | 'samp' | 'small' | 'span' | 'strong' | 'sub' | 'sup' | 'u' | 'var';
export declare type ITextElement = 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'p';
export declare type IViewportThreshold = IBaseSize;
export declare type IWidth = IBaseSize;
export interface IEasyFlexTheme {
    border: {
        radius: IBaseSizeNumber;
        width: IBaseSizeNumber;
    };
    color: {
        primary: IColorCode | IColorKeyword | IColorName;
        secondary: IColorCode | IColorKeyword | IColorName;
        tertiary: IColorCode | IColorKeyword | IColorName;
        quaternary: IColorCode | IColorKeyword | IColorName;
        quinary: IColorCode | IColorKeyword | IColorName;
        senary: IColorCode | IColorKeyword | IColorName;
        warning: IColorCode | IColorKeyword | IColorName;
        error: IColorCode | IColorKeyword | IColorName;
        header: IColorCode | IColorKeyword | IColorName;
        footer: IColorCode | IColorKeyword | IColorName;
        modal: IColorCode | IColorKeyword | IColorName;
        primaryText: IColorCode | IColorKeyword | IColorName;
        secondaryText: IColorCode | IColorKeyword | IColorName;
        tertiaryText: IColorCode | IColorKeyword | IColorName;
        quaternaryText: IColorCode | IColorKeyword | IColorName;
        quinaryText: IColorCode | IColorKeyword | IColorName;
        senaryText: IColorCode | IColorKeyword | IColorName;
        warningText: IColorCode | IColorKeyword | IColorName;
        errorText: IColorCode | IColorKeyword | IColorName;
        headerText: IColorCode | IColorKeyword | IColorName;
        footerText: IColorCode | IColorKeyword | IColorName;
        modalText: IColorCode | IColorKeyword | IColorName;
        primaryBackground: IColorCode | IColorKeyword | IColorName;
        secondaryBackground: IColorCode | IColorKeyword | IColorName;
        tertiaryBackground: IColorCode | IColorKeyword | IColorName;
        quaternaryBackground: IColorCode | IColorKeyword | IColorName;
        quinaryBackground: IColorCode | IColorKeyword | IColorName;
        senaryBackground: IColorCode | IColorKeyword | IColorName;
        warningBackground: IColorCode | IColorKeyword | IColorName;
        errorBackground: IColorCode | IColorKeyword | IColorName;
        headerBackground: IColorCode | IColorKeyword | IColorName;
        footerBackground: IColorCode | IColorKeyword | IColorName;
        modalBackground: IColorCode | IColorKeyword | IColorName;
        onPrimary: IColorCode | IColorKeyword | IColorName;
        onSecondary: IColorCode | IColorKeyword | IColorName;
        onTertiary: IColorCode | IColorKeyword | IColorName;
        onQuaternary: IColorCode | IColorKeyword | IColorName;
        onQuinary: IColorCode | IColorKeyword | IColorName;
        onSenary: IColorCode | IColorKeyword | IColorName;
        onWarning: IColorCode | IColorKeyword | IColorName;
        onError: IColorCode | IColorKeyword | IColorName;
        onHeader: IColorCode | IColorKeyword | IColorName;
        onFooter: IColorCode | IColorKeyword | IColorName;
        onModal: IColorCode | IColorKeyword | IColorName;
        primaryBorder: IColorCode | IColorKeyword | IColorName;
        secondaryBorder: IColorCode | IColorKeyword | IColorName;
        tertiaryBorder: IColorCode | IColorKeyword | IColorName;
        quaternaryBorder: IColorCode | IColorKeyword | IColorName;
        quinaryBorder: IColorCode | IColorKeyword | IColorName;
        senaryBorder: IColorCode | IColorKeyword | IColorName;
        warningBorder: IColorCode | IColorKeyword | IColorName;
        errorBorder: IColorCode | IColorKeyword | IColorName;
        headerBorder: IColorCode | IColorKeyword | IColorName;
        footerBorder: IColorCode | IColorKeyword | IColorName;
        modalBorder: IColorCode | IColorKeyword | IColorName;
    };
    distance: IBaseSizeNumber;
    font: {
        sizeType: ISizeType;
        size: IBaseSizeNumber;
        weight: {
            normal: number | string;
            semibold: number | string;
            bold: number | string;
        };
    };
    modal: {
        backgroundColor: string;
        blur: number;
        blurElementId: string;
        containerElementId: string;
    };
    size: {
        height: IBaseSizeNumber;
        width: IBaseSizeNumber;
    };
    viewport: {
        fallbackThreshold: number;
        threshold: IBaseSizeNumber;
    };
}
export declare type IPartialEasyFlexTheme = IDeepPartial<IEasyFlexTheme>;
