import { FC, HTMLAttributes } from 'react';
import { IAlignSelf, IColor, IDistance, IFontSize, IFontWeight, IHeight, ITextAlign, ITextElement, IWidth, IWordBreak } from '../types';
export interface ITextProps extends HTMLAttributes<HTMLParagraphElement> {
    align?: ITextAlign;
    alignSelf?: IAlignSelf;
    color?: IColor;
    element?: ITextElement;
    fontSize?: IFontSize | number;
    fontWeight?: IFontWeight | number;
    fullHeight?: boolean;
    fullWidth?: boolean;
    height?: IHeight | number;
    italic?: boolean;
    marginBottom?: IDistance | number;
    marginLeft?: IDistance | number;
    marginRight?: IDistance | number;
    marginTop?: IDistance | number;
    marginX?: IDistance | number;
    marginY?: IDistance | number;
    maxHeight?: IHeight | number;
    maxWidth?: IWidth | number;
    minHeight?: IHeight | number;
    minWidth?: IWidth | number;
    paddingBottom?: IDistance | number;
    paddingLeft?: IDistance | number;
    paddingRight?: IDistance | number;
    paddingTop?: IDistance | number;
    paddingX?: IDistance | number;
    paddingY?: IDistance | number;
    width?: IWidth | number;
    wordBreak?: IWordBreak;
}
export declare const Text: FC<ITextProps>;
